<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;net48</TargetFrameworks>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <TargetExt>.gha</TargetExt>
    <RootNamespace>SampleGhTools</RootNamespace>
    <AssemblyName>SampleGhTools</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <OutputPath>..\bin\</OutputPath>
    <NoWarn>NU1701;NETSDK1086</NoWarn>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\ExtrudePlanarCurve_24x24.png" />
    <Content Include="Resources\RectangleCenter_24x24.png" />
    <None Include="Resources\SampleGhTools_24x24.png" />
    <None Include="Resources\FilterInstanceDefinitions_24x24.png" />
    <None Include="Resources\InstanceDefinitionGeometry_24x24.png" />
    <None Include="Resources\InstanceDefinitionProperties_24x24.png" />
    <None Include="Resources\InstanceDefinitions_24x24.png" />
    <None Include="Resources\InstanceObjectProperties_24x24.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="9.0.26146.14285-wip" ExcludeAssets="runtime" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
    <PackageReference Include="System.Resources.Extensions" Version="9.0.0" />
  </ItemGroup>
</Project>
