<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0-windows;net48</TargetFrameworks>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <TargetExt>.rhp</TargetExt>
    <RootNamespace>SampleCsTest2</RootNamespace>
    <AssemblyName>SampleCsTest2</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputPath>..\..\bin\</OutputPath>
    <NoWarn>NU1701;NETSDK1086</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\SampleCs.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SampleCsCommon\SampleCsCommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RhinoCommon" Version="9.0.26146.14285-wip" ExcludeAssets="runtime" />
  </ItemGroup>

</Project>
