<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net9.0-windows;net48</TargetFrameworks>
    <RootNamespace>SampleCsConsole</RootNamespace>
    <AssemblyName>SampleCsConsole</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\..\bin\</OutputPath>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

</Project>
