<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0-windows;net48</TargetFrameworks>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <TargetExt>.rhp</TargetExt>
    <RootNamespace>SampleCsDockBar</RootNamespace>
    <AssemblyName>SampleCsDockBar</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWpf>true</UseWpf>
    <OutputPath>..\bin\</OutputPath>
    <NoWarn>NU1701;NETSDK1086</NoWarn>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\SampleCsDockBar.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RhinoCommon" Version="9.0.26146.14285-wip" ExcludeAssets="runtime" />
    <PackageReference Include="RhinoWindows" Version="9.0.26146.14285-wip" ExcludeAssets="runtime" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
    <PackageReference Include="System.Resources.Extensions" Version="9.0.0" />
  </ItemGroup>

</Project>
