<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>1701;1702;NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Rhino.Inside" Version="8.0.4-beta" />
  </ItemGroup>
</Project>