<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net48</TargetFrameworks>
    <Version>1.0</Version>
    <Title>Test3dmWrite</Title>
    <Description>Description of Test3dmWrite</Description>
    <TargetExt>.rhp</TargetExt>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="EmbeddedResources\**\*" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="RhinoCommon" Version="9.0.26146.14285-wip" IncludeAssets="compile;build" />
  </ItemGroup>
  
</Project>