<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <TargetFrameworks>net481;net8.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Rhino3dm" Version="8.17.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="RectifiedArchimedeanSolids8.3dm" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
