<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SupportedOSPlatformVersion>8.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>1701;1702;NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Rhino.Inside" Version="8.0.6-beta" />
  </ItemGroup>

</Project>
