<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0-windows;net48</TargetFrameworks>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <UseWindowsForms>true</UseWindowsForms>
    <TargetExt>.rhp</TargetExt>
    <RootNamespace>SampleCsMain</RootNamespace>
    <AssemblyName>SampleCsMain</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <OutputPath>..\..\bin\</OutputPath>
    <NoWarn>NU1701;NETSDK1086</NoWarn>
    <Company>Robert McNeel &amp; Associates</Company>
    <Copyright>Copyright © 2013-2026, Robert McNeel &amp; Associates</Copyright>
    <Version>9.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\SampleCs.ico" />
    <Content Include="SampleCsMain.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SampleCsCommon\SampleCsCommon.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="RhinoCommon" Version="9.0.26146.14285-wip" ExcludeAssets="runtime" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
    <PackageReference Include="System.Resources.Extensions" Version="9.0.0" />
  </ItemGroup>
</Project>
