<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0-windows;net48</TargetFrameworks>
    <TargetExt>.rhp</TargetExt>
    <OutputPath>../bin/</OutputPath>
    <OutputType>Library</OutputType>
    <Company>Robert McNeel &amp; Associates</Company>
    <Copyright>Copyright © 2013-2026, Robert McNeel &amp; Associates</Copyright>
    <Product>SampleCsWithLicense</Product>
    <Description>Sample Rhino Licensing Plug-in</Description>
    <Version>9.0.0</Version>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>1701;1702;NU1701</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="RhinoCommon" Version="9.0.26146.14285-wip" />
    <PackageReference Include="RhinoWindows" Version="9.0.26146.14285-wip" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>
