<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net9.0;net48</TargetFrameworks>
    <RootNamespace>SampleGhFileAnalysis</RootNamespace>
    <AssemblyName>SampleGhFileAnalysis</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\bin\</OutputPath>
    <NoWarn>NU1701;NETSDK1086</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="9.0.26146.14285-wip" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
